apiVersion: certmanager.k8s.io/v1alpha2
kind: Certificate
metadata:
  name: zealous-ddns-info-tls
spec:
  secretName: zealous-ddns-info
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: zealous.ddns.info
  dnsNames:
    - zealous.ddns.info
    - www.zealous.ddns.info
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - zealous.ddns.info
          - www.zealous.ddns.info
